name: UI test
description: Run the ui test on a specific image

runs:
  using: composite
  steps:
    - name: Test
      env:
        IMAGE: inspirehep/ui
      shell: bash
      run: >
        docker run
        --pull always
        --network="host"
        $IMAGE:$BUILD_TAG
        yarn test
